README.md
dashboard.py
setup.py
utilities.py
volkswagencarnet.py

My goal was to be able to turn om my car heater for my VW Golf from Home assistant, since the WE-connect app is so slow 😠 .
First time writing Python, but easy to follow the code current code semantics. 
To be able to use the features for cars with `engineTypeCombustian` there is need to provide a S-PIN to those actions. Currently there is only one action (`start_combustion_engine_heating`) that is using it, but will be needed if/when adding other features.
I had some troubles with the `configuration.py` file. It seem to be needed but missing in the repo.
Can't figure out why it did work for some time then suddenly stopped. Saying that the configuration module is missing.
Solved it by creating a new one. But maybe @robinostlund can shed some light for me on why it works for him without …

Add support for combustion engine heating

---

volkswagencarnet.py

This method triggers a request to send an update by a selected car.
Some car doesn't update on its own and needs to be "requested for report" so they can update their data after they got connected to WLAN.
This method adds possiblity to trigger this report generation from API.
Closes #105

Add method to request car to report its state

---

.gitignore
volkswagencarnet.py
vw_dashboard.py

Not sure if this is correct since Im not able to test it myself. It also requires a change in the HA integration.
Something like this
```python
@property
def hvac_mode(self):
"""Return hvac operation ie. heat, cool mode.
Need to be one of HVAC_MODE_*.
"""
if not self.instrument.hvac_mode:
return HVAC_MODE_OFF
hvac_modes = {
'heating': HVAC_MODE_HEAT,
'cooling': HVAC_MODE_COOL,
}
return hvac_modes.get(self.instrument.hvac_mode, HVAC_MODE_OFF)
```
Will make a PR for that if this one makes sense.

Exposes hvac mode on climate model

---

README.md

See #130
Using volkswagencarnet.Connection._login results in an erroneous login state. I propose that the example code in the README.md is changed so that others don't run into the same problem.

Change README example: use doLogin instead of _login

---

vw_connection.py

I also got the "Invalid audience" Error after upgrading to v4.4.36 today.
See issue: [https://github.com/robinostlund/volkswagencarnet/issues/131]
I have no clue why this is happening, but can you disable this verification when checking the expiration of tokens?

disable verification of audience to avoid "Invalid audience" errors on decoding jwt tokens

---

vw_connection.py

This is a fix for https://github.com/robinostlund/volkswagencarnet/issues/136 that have been working well for me for a month. Basic problem is that the potential different homeregions when having more than one vehicle for an account creates "static" urls during login phase in _make_url to be used throughout the session. This leads to that only vehicles with the matching homeregion will get sensor updates, actions etc.

Fix multiple homeregions

---

.github/renovate.json
setup.cfg

@robinostlund do you have strong opinions about dependabot vs renovate? I tested out renovate (which has support for updating the pre-commit versions also), and this is what the onboarding PR says.
Oh, and regarding dependency versions. Runtime dependencies probably should have some ranges defined (I'm fairly sure things would break with ancient versions of some of them), and test/build ones could probably be pinned to exact versions?

Add renovate config

---

tests/fixtures/connection.py
tests/fixtures/constants.py
tests/fixtures/resources/responses/timer.json
tests/integration_test.py
tests/vw_connection_test.py
tests/vw_timer_test.py
tests/vw_utilities_test.py
tests/vw_vehicle_test.py
volkswagencarnet/vw_connection.py
volkswagencarnet/vw_dashboard.py
volkswagencarnet/vw_timer.py
volkswagencarnet/vw_utilities.py
volkswagencarnet/vw_vehicle.py

Relates to https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/352
A little bit of a placeholder still, but goal is to implement some functionality for timer programming etc.
Some data is probably different, if there is an aux heater or something attached, so will probably ask for volunteers to provide API responses at some point :wink: 
The whole departure schedule request is sent on each call to the backend, so including any changes to the charging profiles will update them also

Add timer programming feature

---

tests/integration_test.py
tests/vw_timer_test.py
volkswagencarnet/vw_connection.py
volkswagencarnet/vw_dashboard.py
volkswagencarnet/vw_timer.py
volkswagencarnet/vw_vehicle.py

Add support for heater source in departure timers.
Breaking change! "charging_cable_connected" now returns True for "connected" status

Timerprogramming fixes

---

volkswagencarnet/vw_connection.py
volkswagencarnet/vw_vehicle.py

If the token exchange fails, we can still actually use the service with the short lived sessions

Support continuing without a refresh token

---

tests/vw_vehicle_test.py
volkswagencarnet/vw_const.py
volkswagencarnet/vw_dashboard.py
volkswagencarnet/vw_vehicle.py

Skip the lock entities when remote (un)locking is not supported but still create the binary sensors.

No lock if not supported

---

.pre-commit-config.yaml
volkswagencarnet/vw_vehicle.py

I have a car where the windows in the rear cannot be opened. The API returns a response with the hex codes included, but with the value set to 0 (as it also does for the sunroof). This PR changes the logic for windows to match the logic of the sunroof. 
Additionally, it changes the value for windows_closed to only reflect the status of the actual supported windows, not all windows and changes the corresponding is_windows_closed_supported so that this sensor is only supported if any window is actually supported.
I bumped the Black version in the hopes of being able to run the pre-commit hook as there was an error regarding `cannot import name '_unicodefun' from 'click'`, however the hook is now failing on `mypy` due to some existing code.

Fix window support detection

---

volkswagencarnet/vw_dashboard.py

Update to comply with Home Assistant 2023.05.x
The measuring unit should only be applied to int sensors.
The fix for: https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/474

Update to comply with Home Assistant 2023.05.x

---

volkswagencarnet/vw_dashboard.py
volkswagencarnet/vw_vehicle.py

Integration to Home Assistant has problem with string representation of "Charging time left".
So I changed the value to integer and defined the unit.

Sensor 'Charging time left' as number of minutes

---

volkswagencarnet/vw_connection.py

Hi @oliverrahner,
There is a bug introducing the clean-up commit 3c753a3.
Once you adding integration and enables full debug log:
It's failing with the following error:
```
2023-12-05 12:44:20.412 INFO (MainThread) [volkswagencarnet.vw_connection] Successfully logged in
2023-12-05 12:44:20.412 DEBUG (MainThread) [volkswagencarnet.vw_connection] Fetching vehicles associated with account
2023-12-05 12:44:20.412 DEBUG (MainThread) [volkswagencarnet.vw_connection] HTTP GET "https://emea.bff.cariad.digital/vehicle/v2/vehicles"
2023-12-05 12:44:21.108 ERROR (MainThread) [custom_components.volkswagencarnet.config_flow] Failed to login due to error: 'dict' object has no attribute 'text'
```
This PR revert back the change being done in the clean-up commit.

Fix the bug introduced with the clean-up commit 3c753a3

---

volkswagencarnet/vw_connection.py

@oliverrahner there is an issue with the re-login process.
During the update, you might get a 401 Unauthorized error:
```
2023-12-06 11:10:11.770 DEBUG (MainThread) [volkswagencarnet.vw_connection] Going to call vehicle updates
2023-12-06 11:10:11.771 DEBUG (MainThread) [volkswagencarnet.vw_connection] HTTP GET "https://emea.bff.cariad.digital/vehicle/v1/vehicles/- 
WVXXXX/selectivestatus?jobs=access,fuelStatus,vehicleLights,vehicleHealthInspection,measurements,charging,climatisation,automation"
2023-12-06 11:10:11.773 DEBUG (MainThread) [volkswagencarnet.vw_connection] HTTP GET "https://emea.bff.cariad.digital/vehicle/v2/vehicles"
2023-12-06 11:10:11.775 DEBUG (MainThread) [volkswagencarnet.vw_connection] HTTP GET "https://emea.bff.cariad.digital/vehicle/v1/vehicles/- …
```

Fix Re-Login race condition

---

volkswagencarnet/vw_connection.py
volkswagencarnet/vw_dashboard.py
volkswagencarnet/vw_vehicle.py

Introduction of API Status sensors
The default status for the supported APIs is "Unknown".
The following logic applies to provide a status:
```
if response_code in [200, 204, 207]:
status = "Up"
elif response_code == 401:
status = "Unauthorized"
elif response_code == 403:
status = "Forbidden"
elif response_code == 429:
status = "Rate limited"
elif response_code == 1000:
status = "Error"
else:
status = "Down"
```
FYI @oliverrahner

Introduction of API Status sensors

---

volkswagencarnet/vw_connection.py

A new token is not being set for the Authorization header after the token refresh.
It fixes the issue with the refresh_tokens flow that I've described in this discussion: https://github.com/robinostlund/volkswagencarnet/discussions/224
FYI @oliverrahner

Fix refresh_tokens flow

---

volkswagencarnet/vw_vehicle.py

Fix for Doors and Trunk sensors
Removes duplicate Doors Lock and Trunk Lock sensors and enables.
Lock/Unlock buttons are enabled only if WeConnectPlus subscription is active.
FYI @oliverrahner

Fix for Doors and Trunk sensors

---

volkswagencarnet/vw_vehicle.py

A combined range sensor sensor is not applicable for combustion vehicles.

Fix combined range sensor logic
